### ISSUE TITLE
Create Dogoout logo

### ISSUE THREAD

**Issue by TanguyVandervelden1** [ivo-hr/Dogoout#10]

**Comment by cadezd** [comment]
Change the colors of the logo to this:
1. #331B2F
2.  #A6809F

Gradient goes from color no. 1 to color no. 2

**Comment by TanguyVandervelden1** [comment]
![Capture d'écran 2023-10-26 144642](https://github.com/ivo-hr/Dogoout/assets/95360937/d5a73087-e786-4e0b-a451-6ed96425fccd)
