### ISSUE TITLE
Create PowerPoint presentation.

### ISSUE THREAD

**Issue by cadezd** [ivo-hr/Dogoout#13]
Friday’s presentation roles:

- **David**: Intro, summary, requirements, UI

- **Enrique**: assumptions, dependencies, user personas

- **Tanguy**: development method

- **Jongsoo**: high-level system architecture, use-case diagrams

Also at the end of the presentation we will each quickly explain our work from this week.

**Comment by jsoone24** [comment]
<img width="1187" alt="Screenshot 2023-10-26 at 14 34 44" src="https://github.com/ivo-hr/Dogoout/assets/60023455/25f59a60-aac5-40b5-a4f7-fd155839be9a">

My part of presentation is fine to submit!

**Comment by jsoone24** [comment]
<img width="1185" alt="Screenshot 2023-10-26 at 15 06 05" src="https://github.com/ivo-hr/Dogoout/assets/60023455/7772869a-c9e7-4980-8740-8be039d1f955">

Minor change adding Dogoout Logo
