### ISSUE TITLE
Start filling out Project Plan Template

### ISSUE THREAD

**Issue by cadezd** [ivo-hr/Dogoout#17]
Start filling out project plan template from brightspace... Fill out what you can and know... everythin else we will fill on thursdays meeting

1. Jongsoo:  Overall approach, **Risk register** (10 - 15 risks), **Testing phase**
2. Enrique: Requirements Phase, Technical Requirements, **Testing phase**
3. David Design Phase, Week 1 (designing protoype,  ui design), Week 2 (implementing the design), **Deliverables**
4. Tanguy: Implementation Phase, Week 2 (connecting frontend with backend)
5.  **Everyone: fill out what they did unitl week 6**

**Comment by jsoone24** [comment]
<img width="588" alt="Screenshot 2023-11-02 at 20 01 34" src="https://github.com/ivo-hr/Dogoout/assets/60023455/851a5f7b-d7ed-4962-a495-725420688068">
<img width="585" alt="Screenshot 2023-11-02 at 20 01 50" src="https://github.com/ivo-hr/Dogoout/assets/60023455/87346119-d944-4e4b-9eb9-edb63528c5de">
<img width="591" alt="Screenshot 2023-11-02 at 20 04 48" src="https://github.com/ivo-hr/Dogoout/assets/60023455/d3d627cc-2f76-4f10-9089-f885d8f93c41">
<img width="295" alt="Screenshot 2023-11-09 at 17 59 42" src="https://github.com/ivo-hr/Dogoout/assets/60023455/9635b3fc-1758-4ed9-8879-2cfad80cfc78">
<img width="312" alt="Screenshot 2023-11-09 at 18 00 17" src="https://github.com/ivo-hr/Dogoout/assets/60023455/3b2f0eaf-e96d-4b52-ac30-816f9562f70a">

**Comment by cadezd** [comment]
![image](https://github.com/ivo-hr/Dogoout/assets/58308216/a55bc71f-97f9-4147-87b3-f3d6576379a6)
![image](https://github.com/ivo-hr/Dogoout/assets/58308216/d7dd8d0c-dd2b-480a-9386-237e240d7024)
![image](https://github.com/ivo-hr/Dogoout/assets/58308216/2e68c0d6-8a69-47b9-941b-bc2102079d89)
![image](https://github.com/ivo-hr/Dogoout/assets/58308216/59020989-5096-4433-81e4-181bffa225b9)
