### ISSUE TITLE
Create sequence diagram for matching feature.

### ISSUE THREAD

**Issue by cadezd** [ivo-hr/Dogoout#2]
Create sequence diagram for matching feature and paste it into design document under Detailed System Design section.  Also provide brief description of sequence diagram in document.

**Comment by ivo-hr** [comment]
Finished a crude version of the diagram. I preferred to make it vertical as to comply with the [sequence diagram](https://sequencediagram.org/#) website. It  still needs some polish as it might be difficult to understand. 

Also it is ridiculously long.
![matuching_feature_seqdia](https://github.com/ivo-hr/Dogoout/assets/81875802/9b999dc7-1934-408b-ac33-74d1ec3461af)

**Comment by cadezd** [comment]
Great job, overall i think there are too many details so here i crossed out what i think is unnecessary. Other things that are in red squaras are the things that i dont quite understand. We will discuss changes on Monday's meeting. But overall good.
![276698228-9b999dc7-1934-408b-ac33-74d1ec3461af](https://github.com/ivo-hr/Dogoout/assets/58308216/cd531383-4a9f-4991-9134-8dfd5280fe76)

**Comment by ivo-hr** [comment]
Simplified the matching diagram and added notes for clarification
![dogoout_match_sequence_diagram_v1 0-18oct23](https://github.com/ivo-hr/Dogoout/assets/81875802/bcb80292-a93b-45b1-bd2b-368bc27eab88)

**Comment by cadezd** [comment]
![image](https://github.com/ivo-hr/Dogoout/assets/58308216/01a7b8ab-3f0e-4684-b251-01e92a4ec982)

here i think there should be "User swipes (likes) User 1's profile" but other that that i think its okay... good job

**Comment by ivo-hr** [comment]
oops, spelling mistake!
![dogoout_matching_sequence_diagram_v1 0-19oct23](https://github.com/ivo-hr/Dogoout/assets/81875802/295108c9-faa4-4f46-bad9-361eca84908a)
