### ISSUE TITLE
Create sequence diagram for messaging feature.

### ISSUE THREAD

**Issue by cadezd** [ivo-hr/Dogoout#3]
Create sequence diagram for messaging feature and paste it under Detailed System Design section. Also provide brief description of sequence diagram in document.

**Comment by ivo-hr** [comment]
Finished a crude version of the diagram. I preferred to make it vertical as to comply with the [sequence diagram](https://sequencediagram.org/#) website.
![messaging_feature_seqdia](https://github.com/ivo-hr/Dogoout/assets/81875802/6b5dd6c4-ac66-4621-a17a-195eb2bf1cb6)

**Comment by cadezd** [comment]
Good concept is good.  I would remove arrows that i have maked because personally i think they are too much detail. Overall good job on this one,
![276697966-6b5dd6c4-ac66-4621-a17a-195eb2bf1cb6](https://github.com/ivo-hr/Dogoout/assets/58308216/2c906305-1d6a-46bc-b992-7a5cfb64ce31)

**Comment by ivo-hr** [comment]
fixed the issues and added notes for comprehension:
![dogoout_messaging_sequence_diagram_v1 0-19oct23](https://github.com/ivo-hr/Dogoout/assets/81875802/105c5e99-3fe2-4f0d-832a-33bf65c6e1aa)

**Comment by cadezd** [comment]
Approved

**Comment by ivo-hr** [comment]
Approved by team leader
