### ISSUE TITLE
Create use-case diagram.

### ISSUE THREAD

**Issue by cadezd** [ivo-hr/Dogoout#8]
Create use-case diagram and paste it under Detailed syste mdesign section in Design document. Also provide brief description of diagram.

**Comment by jsoone24** [comment]
approved by the team

![Usecase Diagram 001](https://github.com/ivo-hr/Dogoout/assets/60023455/de980864-c1ad-4e45-add3-48174eef3123)

**Comment by jsoone24** [comment]
![Dogoout_Usecase_Diagram_v1 1-23Oct23](https://github.com/ivo-hr/Dogoout/assets/60023455/1f0d8180-6edf-46b2-87f5-b33717847a97)
Updated with Dogoout Logo
